<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IR-C02PW2DWG8WP" name="innRoad.QAApiTesting.SuiteA.Test2" tests="3" failures="0" timestamp="23 Oct 2015 18:42:45 GMT" time="0.079" errors="1">
  <testcase name="test2" time="0.024" classname="innRoad.QAApiTesting.SuiteA.Test2"/>
  <testcase name="test2" time="0.028" classname="innRoad.QAApiTesting.SuiteA.Test2"/>
  <testcase name="test2" time="0.027" classname="innRoad.QAApiTesting.SuiteA.Test2">
    <error type="org.testng.SkipException" message="Skpping the test Test2 inside the suite SuiteA">
      <![CDATA[org.testng.SkipException: Skpping the test Test2 inside the suite SuiteA
	at innRoad.QAApiTesting.Base.TestBase.validateRunmodes(TestBase.java:45)
	at innRoad.QAApiTesting.SuiteA.Test2.test2(Test2.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- test2 -->
</testsuite> <!-- innRoad.QAApiTesting.SuiteA.Test2 -->
